use ratatui::{buffer::Buffer, layout::Rect, style::Style, symbols::braille::BRAILLE};

use crate::config::Theme;

pub fn fill_background(old: &Rect, new: &Rect, buf: &mut Buffer, theme: Theme) {
    let style = Style::default()
        .bg(ratatui::style::Color::Reset)
        .fg(theme.secondary_bg);
    for y in old.top()..old.bottom() {
        for x in old.left()..old.right() {
            if !(x >= new.left() && x < new.right() && y >= new.top() && y < new.bottom()) {
                buf[(x, y)]
                    .set_char(BRAILLE[bg_noise(x, y) % BRAILLE.len()])
                    .set_style(style);
            } else {
                buf[(x, y)].set_bg(theme.background);
            }
        }
    }
}

// NOTE: no idea what's happening here
// it was generated by llm
fn bg_noise(a: u16, b: u16) -> usize {
    let mut x = ((a as u32) << 16) | (b as u32);
    x ^= x >> 15;
    x = x.wrapping_mul(0x2c1b3c6d);
    x ^= x >> 12;
    x = x.wrapping_mul(0x297a2d39);
    x ^= x >> 15;

    x as usize
}
